-- ==========================================
-- Facility Reservation and Approval System
-- Lab 4 - Section B
-- Database Schema
-- ==========================================

-- ------------------------------------------
-- 1. PROFILES (extends auth.users with a role)
-- ------------------------------------------
CREATE TABLE profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'Requester'
    CHECK (role IN ('Administrator', 'Facility Staff', 'Requester')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ------------------------------------------
-- 2. FACILITIES
-- ------------------------------------------
CREATE TABLE facilities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  facility_name TEXT NOT NULL,
  facility_type TEXT,
  location TEXT,
  capacity INT,
  condition_status TEXT DEFAULT 'Active'
    CHECK (condition_status IN ('Active', 'Maintenance', 'Inactive')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ------------------------------------------
-- 3. RESERVATIONS
-- ------------------------------------------
CREATE TABLE reservations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  facility_id BIGINT REFERENCES facilities(id),
  requester_id UUID REFERENCES auth.users(id),
  purpose TEXT,
  start_time TIMESTAMPTZ NOT NULL,
  end_time TIMESTAMPTZ NOT NULL,
  status TEXT NOT NULL DEFAULT 'Pending'
    CHECK (status IN ('Pending', 'Approved', 'Rejected', 'Scheduled', 'In Use', 'Completed', 'Cancelled')),
  reviewed_by UUID REFERENCES auth.users(id),
  reviewed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),

  -- BR-B4-02: start must precede end
  CONSTRAINT chk_start_before_end CHECK (start_time < end_time)
);

-- ------------------------------------------
-- 4. AUDIT LOGS
-- ------------------------------------------
CREATE TABLE audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_id UUID REFERENCES auth.users(id),
  action TEXT NOT NULL,           -- e.g. 'Submitted', 'Approved', 'Rejected', 'Cancelled', 'Status Changed', 'Facility Updated'
  table_name TEXT NOT NULL,       -- e.g. 'reservations', 'facilities'
  record_id BIGINT,
  details TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ------------------------------------------
-- 5. ROW LEVEL SECURITY
-- ------------------------------------------
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE facilities ENABLE ROW LEVEL SECURITY;
ALTER TABLE reservations ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;

-- Everyone logged in can read their own profile
CREATE POLICY "Users can view own profile" ON profiles
  FOR SELECT USING (auth.uid() = id);

-- Everyone logged in can view facilities
CREATE POLICY "Authenticated users can view facilities" ON facilities
  FOR SELECT USING (auth.role() = 'authenticated');

-- Only Administrators can insert/update/delete facilities
CREATE POLICY "Admins manage facilities" ON facilities
  FOR ALL USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'Administrator')
  );

-- Requesters can view their own reservations; Admin/Staff can view all
CREATE POLICY "View own or all reservations" ON reservations
  FOR SELECT USING (
    requester_id = auth.uid()
    OR EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role IN ('Administrator', 'Facility Staff'))
  );

-- Requesters can insert their own reservations
CREATE POLICY "Requesters create own reservations" ON reservations
  FOR INSERT WITH CHECK (requester_id = auth.uid());

-- Requesters can update only their own Pending reservations (BR-B4-09);
-- Admin/Staff can update any (for approval/status changes)
CREATE POLICY "Update own pending or admin/staff any" ON reservations
  FOR UPDATE USING (
    (requester_id = auth.uid() AND status = 'Pending')
    OR EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role IN ('Administrator', 'Facility Staff'))
  );

-- Audit logs: everyone authenticated can insert (system writes them);
-- only Administrator can read
CREATE POLICY "Insert audit logs" ON audit_logs
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Admins view audit logs" ON audit_logs
  FOR SELECT USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'Administrator')
  );

-- ------------------------------------------
-- 6. SAMPLE DATA
-- ------------------------------------------
INSERT INTO facilities (facility_name, facility_type, location, capacity, condition_status) VALUES
  ('Conference Room A', 'Meeting Room', '2nd Floor, Main Bldg', 20, 'Active'),
  ('Computer Laboratory 1', 'Laboratory', '3rd Floor, IT Bldg', 40, 'Active'),
  ('Gymnasium', 'Sports Facility', 'Ground Floor, Gym Bldg', 200, 'Active'),
  ('Audio Visual Room', 'AV Room', '1st Floor, Main Bldg', 30, 'Maintenance'),
  ('Function Hall', 'Event Hall', '2nd Floor, Admin Bldg', 150, 'Active');

-- NOTE: after creating your first users via Supabase Auth,
-- insert matching rows into profiles, e.g.:
-- INSERT INTO profiles (id, full_name, role) VALUES
--   ('<uuid-of-admin-user>', 'Admin User', 'Administrator'),
--   ('<uuid-of-staff-user>', 'Staff User', 'Facility Staff'),
--   ('<uuid-of-requester-user>', 'Requester User', 'Requester');
